# All .Values.datatypes are parameters that can be changed in the file values.yaml!
{{- if not .Values.volumeExists }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #Which name should the persistenceVolumeClaim have?
  name: {{ tpl .Values.persistence.claimName . | quote }}
  annotations:
    #If skipuninstall is true persistentVolumeClaim won't be deleted, when the deployment will get uninstalled
    {{- if .Values.skipuninstall }}
    "helm.sh/resource-policy": keep
    {{- end }}
spec:
  # Define the storage class name
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    # Define accessmode
    {{- toYaml .Values.persistence.accessModes | nindent 4  }}
  resources:
    requests:
      # Define storage
      storage: {{ .Values.persistence.storage }}
{{- end }}